/**
 * @author generated by eTrice
 *
 * this class contains the main function running component sub_system_ref
 * it instantiates sub_system_ref and starts and ends the lifecycle
 */

package scenario;

import org.eclipse.etrice.runtime.java.modelbase.RTSystem;
import org.eclipse.etrice.runtime.java.modelbase.SubSystemRunnerBase;

public class Node_node_sub_system_refRunner extends SubSystemRunnerBase {

	/**
     * main function
     * creates the main component and starts and stops the lifecycle
     */
	public static void main(String[] args) {
		// instantiate the main component
		RTSystem sys = new RTSystem("log_sys");
		Node_node_sub_system_ref main_component = new Node_node_sub_system_ref(sys, "sub_system_ref");
		
		run(main_component, args);
	}
};
